import bodyParser from "body-parser";
import express from "express";
import { RegisterRoutes } from "./routes";

const app = express();
app.use(bodyParser.json());

// Auto-generated by TSOA
RegisterRoutes(app);

// Health check
app.get("/", (_, res) => {
  res.send("TSOA Todo API");
});

const port = 3000;
app.listen(port, () =>
  console.log(`Server running at http://localhost:${port}`)
);
